name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]  # Updates every 6 hours
  workflow_dispatch:                # Allow manual runs

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}