name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]  # Updates every 6 hours
  workflow_dispatch:                # Allow manual runs

jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: metrics-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 15
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: main
          committer_message: "chore(metrics): update github-metrics.svg"
          user: ${{ github.repository_owner }}
          template: classic
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_stars: yes
          plugin_achievements: yes